source 'https://rubygems.org'


gem 'rails', '4.2.5.2'
gem 'pg'
gem 'rails-api'
gem 'rack-cors', :require => 'rack/cors'
gem 'byebug'
gem 'puma'
gem 'staccato'

group :development do
  gem 'capistrano',         require: false
  gem 'capistrano-rvm',     require: false
  gem 'capistrano-rails',   require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano3-puma',   require: false
  gem 'spring'
end
