export const COMMANDS = {
  TOGGLE_PLAY_PAUSE: "TOGGLE_PLAY_PAUSE",
  PLAY_PREV_SONG: "PLAY_PREV_SONG",
  PLAY_NEXT_SONG: "PLAY_NEXT_SONG"
};

export const PLAYER_STATES = {
  UNSTARTED: -1,
  ENDED: 0,
  PLAYING: 1,
  PAUSED: 2,
  BUFFERING: 3,
  VIDEO_CUED: 5,
  ERROR: 6
};
